# Generated by Django 5.1.6 on 2025-03-13 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhello', '0002_course_table_delete_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_table',
            old_name='CourseTitlet',
            new_name='CourseTitle',
        ),
    ]
